package infoP;
// Generated Jan 28, 2017 10:30:50 PM by Hibernate Tools 4.3.1



/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer id;
     private Userinfo userinfo;
     private String message;
     private String toNumber;
     private String date;

    public Messages() {
    }

	
    public Messages(Userinfo userinfo, String toNumber) {
        this.userinfo = userinfo;
        this.toNumber = toNumber;
    }
    public Messages(Userinfo userinfo, String message, String toNumber, String date) {
       this.userinfo = userinfo;
       this.message = message;
       this.toNumber = toNumber;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String gettoNumber() {
        return this.toNumber;
    }
    
    public void settoNumber(String toNumber) {
        this.toNumber = toNumber;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


