package infoP;
// Generated Jan 28, 2017 10:30:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String password;
     private String name;
     private String surname;
     private String number;
     private String adress;
     private String country;
     private Set<Contacts> contactses = new HashSet<Contacts>(0);
     private Set<Messages> messageses = new HashSet<Messages>(0);

    public Userinfo() {
    }

	
    public Userinfo(String username, String password, String name, String country) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.country = country;
    }
    public Userinfo(String username, String password, String name, String surname, String number, String adress, String country, Set<Contacts> contactses, Set<Messages> messageses) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.surname = surname;
       this.number = number;
       this.adress = adress;
       this.country = country;
       this.contactses = contactses;
       this.messageses = messageses;
    }
    boolean update;

    public boolean isUpdate() {
        return update;
    }
    public void setUpdate(boolean update) {
        this.update = update;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Set<Contacts> getContactses() {
        return this.contactses;
    }
    
    public void setContactses(Set<Contacts> contactses) {
        this.contactses = contactses;
    }
    public Set<Messages> getMessageses() {
        return this.messageses;
    }
    
    public void setMessageses(Set<Messages> messageses) {
        this.messageses = messageses;
    }




}


